using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExperienceGenerator.Location
{
    public class CountryNames
    {
        public static List<string> GetCountryNames()
        {
            List<string> result = new List<string>()
            {
               "Republic of Korea",
"Mexico",
"Canada",
"South Africa",
"United States",
"United States",
"Republic of Korea",
"Brazil",
"Canada",
"Italy",
"United States",
"Sweden",
"United States",
"Spain",
"United States",
"Sweden",
"United States",
"Austria",
"United States",
"Croatia",
"United Kingdom",
"United States",
"United States",
"United States",
"United States",
"United States",
"Canada",
"United States",
"Republic of Korea",
"France",
"United States",
"United Kingdom",
"United States",
"Russia",
"Egypt",
"China",
"Japan",
"Pakistan",
"United States",
"United States",
"Russia",
"Japan",
"India",
"Republic of Korea",
"Paraguay",
"United States",
"China",
"China",
"Taiwan",
"Republic of Korea",
"China",
"China",
"United States",
"Chile",
"India",
"China",
"China",
"India",
"United States",
"China",
"China",
"Russia",
"Canada",
"United States",
"United States",
"China",
"Chile",
"France",
"United States",
"United Kingdom",
"United States",
"United Kingdom",
"United Kingdom",
"United States",
"United States",
"United States",
"United States",
"United States",
"United States",
"United States",
"France",
"United States",
"Canada",
"United States",
"United Kingdom",
"United States",
"United States",
"Spain",
"United States",
"United States",
"Japan",
"United States",
"Sweden",
"United States",
"France",
"Japan",
"Russia",
"United States",
"China",
"China",

            };

            return result;
        }
    }
}
